-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_Finor is

  constant IPBUS_SEL_WIDTH: positive := 2;
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_Finor(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically generated VHDL (Thu Apr 21 16:50:18 2022)
  constant N_SLV_SLR0_MONITOR: integer := 0;
  constant N_SLV_SLR2_MONITOR: integer := 1;
  constant N_SLV_SLR1_MONITOR: integer := 2;
  constant N_SLAVES: integer := 3;
-- END automatically generated VHDL

    
end ipbus_decode_Finor;

package body ipbus_decode_Finor is

  function ipbus_sel_Finor(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically generated VHDL (Thu Apr 21 16:50:18 2022)
    if    std_match(addr, "--00----------------------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_SLR0_MONITOR, IPBUS_SEL_WIDTH)); -- SLR0_monitor / base 0x80000000 / mask 0x30000000
    elsif std_match(addr, "--01----------------------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_SLR2_MONITOR, IPBUS_SEL_WIDTH)); -- SLR2_monitor / base 0x90000000 / mask 0x30000000
    elsif std_match(addr, "--10----------------------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_SLR1_MONITOR, IPBUS_SEL_WIDTH)); -- SLR1_monitor / base 0xa0000000 / mask 0x30000000
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_Finor;

end ipbus_decode_Finor;
