include:
  - project: cms-cactus/phase2/firmware/ci-templates
    ref: v0.1.3
    file: 
      - pipelines/workflow.yml
      - templates/xilinx/build-emp.yml

.ci_templates_ref: v0.1.4

variables:
  QUESTASIM_VERSION: "2021.1_2"
  VIVADO_VERSION: "2021.1"
  BUILD_DIR: "build"
  MTI_VCO_MODE: "64"
  # HARDWARE_TEST_IMAGE_TAG: v0-3-17

serenity_vu13p:build:
  extends: .vivado_build_emp
  variables:
    PROJECT_NAME: p2gt_finor_serenity-vu13p
    PROJECT_DIR_PATH: finor-hdl
    PROJECT_DEPFILE: top_serenity_vu13p-so2.d3
