import struct
import numpy as np


def string_to_binary_array_method1(input_string):
    binary_array = [bin(ord(char))[2:].zfill(8) for char in input_string]
    return binary_array


def pack_in4char(string):
    string_padded = string.ljust(64)
    bin_char = string_to_binary_array_method1(string_padded)
    bin_char_32b = []
    for i in range(16):
        bin_char_32b.append(bin_char[i * 4 + 3] + bin_char[i * 4 + 2] + bin_char[i * 4 + 1] + bin_char[i * 4 + 0])

    return bin_char_32b


algos = ["L1_Mu10er2p3_Jet32er2p3_dR_Max0p4_DoubleJet32er2p3_dEta_Max1p6", "L1_DoublePFJet_MassMin",
         "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT",
         "L1_TkMu_PfJet_dRMax_DoubleJet_dEtaMax", "L1_DoublePFJet_MassMin", "L1_DoubleTkMu0er1p5_SQ_OS_dR_Max1p4",
         "L1_SingleTkMu", "L1_DoubleEGEle", "L1_DoublePFJet_MassMin", "L1_DoublePFJet_dEtaMax", "L1_DoubleTkEle",
         "L1_DoubleTkEle_PFHTT", "L1_DoubleTkMu4_SQ_OS_dR_Max1p2", "L1_DoubleTkMu4p5er2p0_SQ_OS_Mass7to18",
         "L1_DoubleTkMu_PfHTT", "L1_DoubleTkMu_PfJet_PfMet", "L1_DoubleTkMu_TkEle", "L1_DoubleTkPhoIso", "L1_PFHTT"]
print(len(algos))

bin_char_32b_array = []
for string in algos:
    bin_char_32b = pack_in4char(string)
    bin_char_32b_array.append(bin_char_32b)

# print(bin_char_32b_array)

with open('../finor-hdl/firmware/hdl/RAM_init_files/menu_algo_string.mif', 'w') as f:
    for chars in bin_char_32b_array:
        for value in chars:
            f.write(f"{value}\n")

test = string_to_binary_array_method1("L1_Mu10er2p3_Jet32er2p3_dR_Max0p4_DoubleJet32er2p3_dEta_Max1p6")
print(len(test))